<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= '商品类目管理';
$lang['error_must_select']			= '你必须选择一个类别来整理';
$lang['error_not_found']			= '所请求的类不能被找到。';
$lang['organize_category']			= '整理 "%s" 分类';
$lang['organize']					= '整理';
$lang['category_id']				= 'ID';
$lang['category_form']				= '添加新分类';
$lang['name']						= '名字';
$lang['slug']						= '自定义URL地址名';
$lang['description']				= '描述';
$lang['excerpt']					= '摘要';
$lang['sequence']					= '序列号';
$lang['image']						= '图片';
$lang['seo_title']					= 'SEO 标题';
$lang['meta']						= 'Meta 数据';
$lang['message_category_saved']		= '分类已保存';
$lang['error_file_upload']			= '<p>您没有选择要上传的文件。</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= '分类已删除';
$lang['current_file']				= '当前文件';
$lang['confirm_delete_category']	= '你确定要删除这个分类';
$lang['add_new_category']			= '添加一个新分类';
$lang['no_categories']				= '当前没有分类';
$lang['attributes']					= '属性';
$lang['seo']						= 'SEO';
$lang['parent']						= '上级目录';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= '拖放产品可以对其排序';
$lang['sku']						= '货号';
$lang['price']						= '原价';
$lang['sale']						= '售价';
$lang['max_file_size']				= '最大尺寸';
$lang['sync_eelly_category']        = '同步衣联分类';
$lang['request_data_error'] = '请求数据出错';